// Generated schema artifact from crm.sql
// This file is auto-generated by SchemaBuilder.buildSchemaFromSQL()

import { buildSchemaFromSQL } from './SchemaBuilder.js';
import { readFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const ddlPath = join(__dirname, '../../crm_postgres.sql');
const ddl = readFileSync(ddlPath, 'utf-8');

export const crmSchema = buildSchemaFromSQL(ddl, {
  sessionAnchorTables: ['workspaces']
});
